title = 'Phi'
baseURL = 'https://y-phi.github.io/hugo-phi'
defaultContentLanguage = 'en'
mainSections = ['posts']
[taxonomies]
category = 'categories'
tag = 'tags'
series = 'series'
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions.cjk]
enable = true
eastAsianLineBreaks = true
eastAsianLineBreaksStyle = 'css3draft'
escapedSpace = true